language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
    - cd ./Project/Termgine
    - dotnet restore
    - dotnet build
    - dotnet test ../Tests/Termgine.Tests/Termgine.Tests.csproj
